### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by netdrag** [Invertus/PrestaShop-ElasticSearch#14]
There are no images in the search results. 
Please add this line to 
controllers/front/elasticsearch.php on line 143:

$row['id_image'] = $product['_source']['id_image'];
and the images get loaded.

**Comment by rokaszygmantas** [comment]
Thanks for your help! Please don't hesitate to contribute with a pull request next time :)

**Comment by netdrag** [comment]
I would like to... as soon I have the time to figure out how that works :)

**Comment by sarjon** [comment]
Thanks for your help, the issue is fixed now.
