### ISSUE TITLE
Show products from subcategories not working

### ISSUE THREAD

**Issue by slimak12** [Invertus/PrestaShop-ElasticSearch#15]
Hi, 

I have switch on "Show products from subcategories"
http://imgur.com/a/H8Jji
it`s showing only on filter but not in produt list. Could you check it?

**Comment by slimak12** [comment]
Also I found another issu.
Product without image after use filter
Solve
Add `$row['id_image'] = $product['_source']['id_image'];` in `ElasticSearchFilter.php` after ine 320 to get filtered product with image

**Comment by sarjon** [comment]
Hi, thanks for using our module. 
We have just fixed images in filter results and we will check problem with subcategories.
