### ISSUE TITLE
Not showing all filters

### ISSUE THREAD

**Issue by slimak12** [Invertus/PrestaShop-ElasticSearch#16]
Hi,
I have really problem with get all the feature values in filter list. Currenty limit is 10 feature_values in list. (Chang limits in admin dosen`t help)
Can I somehow fix it?

eq. http://imgur.com/a/3rzE0 I have only 10 values of year, but it should be about 200 ( in admin I choose no_limit _

**Comment by sarjon** [comment]
Hi, thanks for you feedback. 

We will take a look at this issue and let you know.
